name: Build Excutable

on:
  push:
    workflow_dispatch:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install xorg-dev (ubuntu only)
      if: ${{ matrix.platform == 'ubuntu-latest' }}
      run: sudo apt-get update && sudo apt-get install -y xorg-dev

    - name: Build
      run: |
        mkdir build 
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Save Linux Artifacts
      if: ${{ matrix.platform == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: Linux Executable
        path: build/app

    - name: Save macOS Artifacts
      if: ${{ matrix.platform == 'macos-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: macOS Executable
        path: build/app

    - name: Save Windows Artifact
      if: ${{ matrix.platform == 'windows-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: Windows Executable
        path: build/Release/app.exe